version: '3'

services:
  points:
    image: points:latest
    build:
      context: .
      dockerfile: points.dockerfile
    restart: always
    network_mode: "host"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - points.env

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: EGS2324pass!
      MYSQL_DATABASE: POINTS
    ports:
      - 3305:3306
    volumes:
      - db_data:/data/db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  db_data: