version: '3'

services:
  web:
    image: webapp:latest
    build:
      context: .
      dockerfile: webapp.dockerfile
    command: python3 manage.py runserver 3000 --noreload
    depends_on:
      - database
    env_file:
      - webapp.env
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webapp
    ports:
      - "3307:3306"
    volumes:
      - db_data:/data/db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: